apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptoweb
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cryptoweb
  template:
    metadata:
      labels:
        app: cryptoweb
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: cryptoweb-secret
      containers:
      - name: cryptoweb
        image: cryptoweb
        command: [ "python", "./main.py" ]
        env:
        - name: MARKET
          valueFrom:
            configMapKeyRef:
              key: market
              name: cryptoweb-cfmap
        - name: CURRENCY
          valueFrom:
            configMapKeyRef:
              key: currency
              name: cryptoweb-cfmap
        imagePullPolicy: Never
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/usr/app/src/secret/"
        ports:
        - containerPort: 8888
          hostPort: 8888