apiVersion: v1
kind: Service
metadata:
  name: cryptoweb-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: cryptoweb
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
